# playbooks/job1_collect_info.yml
- name: Collect basic system info
  hosts: all
  gather_facts: yes
  tasks:
    - name: Build host info list per host
      set_fact:
        host_entry:
          hostname: "{{ ansible_hostname }}"
          date: "{{ ansible_date_time.date }}"
          bios: "{{ ansible_bios_version | default('N/A') }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Show per-host entry
      debug:
        var: host_entry

    - name: Save each host_entry into hostvars
      set_fact:
        collected_entry: "{{ host_entry }}"

- name: Combine all host entries into one list
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Aggregate host entries
      set_fact:
        my_custom_list: "{{ groups['all'] | map('extract', hostvars, 'collected_entry') | list }}"

    - name: Show aggregated list
      debug:
        var: my_custom_list
