# playbooks/job1_collect_info.yml
- name: Collect basic system info
  hosts: all
  gather_facts: yes
  tasks:
    - name: Build host info list
      set_fact:
        host_entry:
          hostname: "{{ ansible_hostname }}"
          date: "{{ ansible_date_time.date }}"
          bios: "{{ ansible_bios_version | default('N/A') }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Show per-host entry
      debug:
        var: host_entry

    - name: Save to global list
      set_stats:
        data:
          my_custom_list: "{{ my_custom_list | default([]) + [ host_entry ] }}"

# Second play just for displaying the combined list
- name: Show final combined list
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display aggregated my_custom_list
      debug:
        var: my_custom_list